name: cariin_buku
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  hugeicons: ^0.0.11
  lottie: ^3.3.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/
    - assets/lottie/
    - assets/images/
